[Settings]
; =========================
; 全局功能开关 / Global Switches
; =========================

# 开启 EPG 功能，支持频道显示预告内容；可选值: True, False | Enable EPG function, support channel display preview content; Optional values: True, False
open_epg = False

; =========================
; 结果输出 & 服务配置 / Output & Service
; =========================

# 模板文件路径；默认值: config/demo.txt | Template file path; Default value: config/demo.txt
source_file = config/user_demo.txt
