[Settings]
; =========================
; 全局功能开关 / Global Switches
; =========================



; =========================
; 结果输出 & 服务配置 / Output & Service
; =========================

# 模板文件路径；默认值: config/demo.txt | Template file path; Default value: config/demo.txt
source_file = config/user_demo.txt
